apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: oscaris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_IP_ADDRESS
              value: "$(POD_IP)"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "$(POD_IP)"
            - name: SERVER_PORT
              value: "8000"
            - name: SPRING_APPLICATION_NAME
              value: "AUTH-SERVICE"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Kevin@123"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://oscaris-pg:5432/oscaris_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "kevin"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "60000"  # 60s
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_DATA_JPA_REPOSITORIES_ENABLED
              value: "true"
            - name: SPRING_JPA_DEFERRED_REPOSITORY_INITIALIZATION
              value: "true"
            - name: SPRING_JPA_MAPPING_CONTEXT_PATH
              value: "classpath*:**/*.class"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_JPA
              value: "DEBUG"
            - name: SECURITY_JWT_SECRET_KEY
              value: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
            - name: SECURITY_JWT_EXPIRATION_TIME
              value: "3600000"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          image: localhost:32000/oscaris-auth-service:1.2
          imagePullPolicy: Always
          name: auth
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
