apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: company-service
  name: company-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: company-service
  template:
    metadata:
      labels:
        io.kompose.service: company-service
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://oscaris-mongo-caterers:27017/oscaris_db
          image: oscaris-company-service:latest
          name: oscaris-company-service
      restartPolicy: Always
