apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-client
  namespace: oscaris
  labels:
    app: discovery-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-client
  template:
    metadata:
      labels:
        app: discovery-client
    spec:
      containers:
        - name: discovery-client
          image: localhost:32000/oscaris-discovery-service:latest
          ports:
            - containerPort: 8761
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
