apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: invoice-service
  name: invoice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: invoice-service
  template:
    metadata:
      labels:
        io.kompose.service: invoice-service
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://oscaris-mongo-caterers:27017/oscaris_db
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: oscaris-invoice-service:latest
          name: oscaris-invoice-service
      restartPolicy: Always
