apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: oscaris-sqlserver
  name: oscaris-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oscaris-sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: oscaris-sqlserver
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - |2
                /opt/mssql/bin/sqlservr &

                echo 'Waiting for SQL Server to start...'
                for i in {1..30}; do
                  /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kevin@123' -Q 'SELECT 1' && break
                  sleep 2
                done

                echo 'Creating database oscaris-db...'
                /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kevin@123' -i /docker-entrypoint-initdb/init.sql

                wait
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: Kevin@123
          image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
          name: oscaris-sqlserver
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlserver-data
            - mountPath: /docker-entrypoint-initdb
              name: oscaris-sqlserver-cm1
      restartPolicy: Always
      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-data
        - configMap:
            name: oscaris-sqlserver-cm1
          name: oscaris-sqlserver-cm1
