apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: oscaris-sqlserver
  name: oscaris-sqlserver
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: oscaris-sqlserver
