spring.datasource.url=jdbc:postgresql://oscaris-pg:5432/oscaris_db
spring.datasource.username=kevin
spring.datasource.password=Kevin@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=AUTH-SERVICE

server.port=8000

# JWT secret key
security.jwt.secret-key =5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
security.jwt.expiration-time=3600000

springdoc.api-docs.path=/api-docs

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
eureka.client.instance.prefer-ip-address=true
#spring.data.mongodb.uri=mongodb://oscaris-mongo-caterers:27017/oscaris_db


