logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://oscaris-discovery-service:8761/eureka/


server:
  port:
    session:
      cookie:
        same-site: None
        secure: true
