apiVersion: v1
kind: Service
metadata:
  name: oscaris-pg
  namespace: oscaris
  labels:
    app: oscaris-pg
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: oscaris-pg

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oscaris-pg
  namespace: oscaris
  labels:
    app: oscaris-pg
spec:
  serviceName: oscaris-pg
  replicas: 1
  selector:
    matchLabels:
      app: oscaris-pg
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
        storageClassName: microk8s-hostpath
  template:
    metadata:
      labels:
        app: oscaris-pg
    spec:
      containers:
        - name: oscaris-pg
          image: localhost:32000/postgres:13
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: oscaris-pg-config
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: oscaris-pg-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
#              value: kevin
              valueFrom:
                secretKeyRef:
                  name: oscaris-pg-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
#              value: Kevin@123
              valueFrom:
                secretKeyRef:
                  name: oscaris-pg-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB) -h localhost
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $(POSTGRES_USER) -h localhost
            initialDelaySeconds: 60
            periodSeconds: 30