apiVersion: v1
kind: Service
metadata:
  name: discovery-client-service
spec:
  type: NodePort
  selector:
    app: discovery-client
  ports:
    - port: 8761          # internal cluster port
      targetPort: 8761    # container port (where the app listens)
      nodePort: 30080     # host port (what you hit from outside)
